name: cih_first_app
description: Ecascade notes offline version.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  flutter_svg: ^2.0.4
  fluttertoast: ^8.2.2
  connectivity_plus: ^4.0.1
  flutter_markdown: ^0.6.15
  flash: ^3.0.5+1
  image_picker: ^0.8.9
  file_selector_linux: ^0.9.1+3
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3
  firebase_database: ^10.2.3
  firebase_storage: ^11.2.0
  firebase_performance: ^0.9.2+3
  dio: ^5.2.1+1
  cached_network_image: ^3.2.3
  animated_text_kit: ^4.2.2
  flutter_tts: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  font_awesome_flutter: ^10.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/DPC.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  fonts:
    - family: Alkatra
      fonts:
        - asset: fonts/Alkatra-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Playfair
      fonts:
        - asset: fonts/PlayfairDisplay-Regular.ttf
    - family: Rubik
      fonts:
        - asset: fonts/RubikPixels-Regular.ttf


  assets:
     - assets/images/
     - assets/images/vegcuts/
     - assets/images/stocksoupssauces/
     - assets/images/spongeBiscuitsCakes/
     - assets/images/breadDoughProducts/
     - assets/images/pastaRiceEggs/
     - assets/images/basicPastryProducts/

     - assets/markdowns/kitchen101/
     - assets/markdowns/stocksoupsauces/
     - assets/markdowns/biscuit_cakes_sponges/
     - assets/markdowns/Bread_dough_products/
     - assets/markdowns/pasta_rice_eggs/
     - assets/markdowns/basic_pastry_products/
     
     - fonts/Alkatra-Regular.ttf
