// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIplv7sEopkVXHljqo5VHUR39Ej2ljCsM',
    appId: '1:679162173715:web:ff31b69679b4cfc08422e6',
    messagingSenderId: '679162173715',
    projectId: 'ecascade-9c192',
    authDomain: 'ecascade-9c192.firebaseapp.com',
    databaseURL: 'https://ecascade-9c192-default-rtdb.firebaseio.com',
    storageBucket: 'ecascade-9c192.appspot.com',
    measurementId: 'G-W2P78KFMXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlQpM-K7tXK-Ve3gZzy2rIfmtvv42x9QY',
    appId: '1:679162173715:android:5a455cf4feebc4948422e6',
    messagingSenderId: '679162173715',
    projectId: 'ecascade-9c192',
    databaseURL: 'https://ecascade-9c192-default-rtdb.firebaseio.com',
    storageBucket: 'ecascade-9c192.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzP0budSNIkXG8nwhbmp281QETsWCK8VE',
    appId: '1:679162173715:ios:d956433df680bb3a8422e6',
    messagingSenderId: '679162173715',
    projectId: 'ecascade-9c192',
    databaseURL: 'https://ecascade-9c192-default-rtdb.firebaseio.com',
    storageBucket: 'ecascade-9c192.appspot.com',
    iosClientId:
        '679162173715-cvme3q7ln47jsfh1uhlqhnqvvp7abb7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cihFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzP0budSNIkXG8nwhbmp281QETsWCK8VE',
    appId: '1:679162173715:ios:d956433df680bb3a8422e6',
    messagingSenderId: '679162173715',
    projectId: 'ecascade-9c192',
    databaseURL: 'https://ecascade-9c192-default-rtdb.firebaseio.com',
    storageBucket: 'ecascade-9c192.appspot.com',
    iosClientId:
        '679162173715-cvme3q7ln47jsfh1uhlqhnqvvp7abb7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cihFirstApp',
  );
}
