name: Build and Deploy APK

on:
  push:
    branches:
      - DPC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create 'builds' branch if it doesn't exist
        run: |
          git branch -a | grep "remotes/origin/builds$" || git checkout -b builds

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.4'  

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Commit and push APK to 'builds' branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout builds
          git add .
          git commit -m "Auto-built APK from DPC branch"
          git push origin builds
