name: Flutter APK Builder

on:
 push:
    branches:
      - DPC

jobs:
 build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK to Google Drive
      uses: nektos/act-google-drive-uploader@v2.1.1
      with:
        folderId: '1q2Gj6HX0z-O9FQkvv8hXy-b2wR3ASejo'
        fileName: 'app-release.apk'
        sourceFilePath: 'build/app/outputs/flutter-apk/app-release.apk'
        credentialsJson: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}