name: Build and Push APK to Google Drive

on:
  push:
    branches:
      - DPC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          echo "Building APK..."
          flutter build apk --release
          APK_PATH=$(find $GITHUB_WORKSPACE -name '*.apk')
          echo "APK Path: $APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV

  push-to-drive:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Decode Google Drive credentials
        run: echo ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }} | base64 -d > credentials.json

      - name: Set Google application credentials
        run: export GOOGLE_APPLICATION_CREDENTIALS=credentials.json

      - name: Upload APK to Google Drive
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: ${{ env.APK_PATH }}
          destination: /path/in/google/drive/app-release.apk
          parent: 1q2Gj6HX0z-O9FQkvv8hXy-b2wR3ASejo
          process_gcloudignore: false
