name: Flutter APK Builder

on:
 push:
    branches:
      - DPC

jobs:
 build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Copy APK to apks directory
      run: |
        mkdir -p apks
        cp -v build/app/outputs/flutter-apk/app-release.apk apks/

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: "Update APKs"
        commit_options: "--all"
        push_options: "--all"
      env:
        GITHUB_TOKEN: "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"