name: Build and Release APK

on:
  push:
    branches:
      - DPC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          echo "Building APK..."
          flutter build apk --release
          APK_PATH=$(find $GITHUB_WORKSPACE -name '*.apk')
          echo "APK Path: $APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV

  create-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Changes in this release:
            - Describe any changes or release notes here.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ needs.build.outputs.apk-path }}
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
