name: Flutter APK Builder

on:
  push:
    branches:
      - DPC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Decode Google Drive credentials
        run: echo ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }} | base64 -d > credentials.json

      - name: Set Google application credentials
        run: export GOOGLE_APPLICATION_CREDENTIALS=credentials.json

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to Google Drive
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk
          parent: 1q2Gj6HX0z-O9FQkvv8hXy-b2wR3ASejo
          process_gcloudignore: false
