name: DPC Build APK and Upload (Quick Test)

on:
  push:
    branches:
      - DPC

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create test JSON file
        run: echo '{"message": "This is a test JSON file."}' > apps/test-file.json

      - name: Display test JSON file content
        run: cat apps/test-file.json

      - name: Commit and Push test JSON file to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add apps/test-file.json
          git commit -m "Add test JSON file"
          git remote rm origin
          git remote add origin "https://github.com/7442charles/flutter1-cih.git"
          git push --force origin HEAD:${{ github.ref }}
        env:
          WORKFLOW_2: ${{ secrets.WORKFLOW_2 }}
