name: DPC Build APK and Upload

on:
  push:
    branches:
      - DPC

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Archive APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Clone target repository
        run: |
          git config --global user.name "7442charles"
          git config --global user.email "cking6951@gmail.com"
          git clone https://github.com/7442charles/ecascade_app_release target-repo

      - name: Create target directory if it doesn't exist
        run: mkdir -p target-repo/app_file/DPC

      - name: Copy APK to target directory
        run: cp -r build/app/outputs/flutter-apk/app-release.apk target-repo/app_file/DPC/

      - name: Push changes to target repository
        working-directory: ./target-repo
        run: |
          git add .
          git commit -m "Add APK for DPC branch"
          git push
